---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: don
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: don
    spec:
      restartPolicy: Always

      containers:
        - name: don
          image: eu.gcr.io/wire-bot/don:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: don-knows
                  key: token

          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /bots/status
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10

          # for L7 LB
          readinessProbe:
            httpGet:
              path: /bots/status
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 60

          volumeMounts:
            - name: disk
              mountPath: /var/lib/don/crypto

            - name: config
              mountPath: /etc/don

          command:
            - "/usr/bin/java"
            - "-Ddw.auth=$(TOKEN)"
            - "-jar"
            - "don.jar"
            - "server"
            - "/etc/don/don.yaml"

      volumes:
        - name: disk
          gcePersistentDisk:
            pdName: don-disk
            fsType: ext4

        - name: config
          configMap:
            name: don-config

---
apiVersion: v1
kind: Service
metadata:
  name: don
spec:
  selector:
    name: don
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP